<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersWithComments()
    {
        $dql = 'SELECT u,c FROM AppBundle\Entity\User u LEFT JOIN u.comments c';
        $q = $this->getEntityManager()->createQuery($dql);
        return $q->getResult();
    }

    public function getUsersWithComments2()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u, c')
            ->leftJoin('u.comments', 'c');
        $q = $qb->getQuery();
        return $q->getResult();
    }
}
